FROM nginx:1.19.3-alpine
LABEL description="django_groceries_challenge" \
      version="0.1" \
      maintainer="StanislavBerezovskii" \
      deployer="https://github.com/StanislavBerezovskii"
COPY nginx.conf /etc/nginx/templates/default.conf.template