version: '3.8'

services:
    project_database:
        image: postgres:15-alpine
        volumes:
            - /var/lib/postgresql/data/
        env_file:
            - ./.env

    project_backend:
        image: stanislavberezovskii/django_groceries_challenge-project_backend:latest
        restart: always
        volumes:
            - static_vol:/app/static
            - media_vol:/app/media
        depends_on:
            - project_database
        env_file:
            - ./.env

    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_vol:/var/html/static/
            - media_vol:/var/html/media/
        depends_on:
            - project_backend

volumes:
    static_vol:
    media_vol: